# Generated by Django 3.1.5 on 2021-02-04 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0002_auto_20210202_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.IntegerField()),
                ('monthly_expenses', models.IntegerField()),
                ('avaliable_to_invest', models.IntegerField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('savings_account', models.IntegerField()),
                ('insurance_account', models.IntegerField()),
                ('investment_account', models.IntegerField()),
                ('savings_account_percentage', models.IntegerField(default=0.5, null=True)),
                ('insurance_account_percentage', models.IntegerField(default=0.25, null=True)),
                ('investment_account_percentage', models.IntegerField(default=0.25, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
