# Generated by Django 3.1.5 on 2021-02-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20210204_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentinfo',
            name='insurance_account_percentage',
            field=models.IntegerField(default=25, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='investment_account_percentage',
            field=models.IntegerField(default=25, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='savings_account_percentage',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
