# Generated by Django 3.1.5 on 2021-02-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20210204_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentinfo',
            old_name='User',
            new_name='user',
        ),
    ]
