# Generated by Django 3.1.5 on 2021-02-10 22:44

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0007_auto_20210204_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='investmentinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='monthly_expenses',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='monthly_income',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
