# Generated by Django 3.1.5 on 2021-02-11 08:52

import Main.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0008_auto_20210210_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='Insurance', editable=False, max_length=50)),
                ('investmentMarkets', models.CharField(choices=[('Whole Life', 'Whole Life'), ('LTCA rider', 'LTCA rider'), ('SWL', 'SWL')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='Investment', editable=False, max_length=50)),
                ('investmentMarkets', models.CharField(choices=[('Mutual Funds', 'Mutual Funds'), ('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('ETFs', 'ETFs')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='Savings', editable=False, max_length=50)),
                ('investmentMarkets', models.CharField(choices=[('Family Support', 'Family Support'), ('Major Purchases', 'Major Purchases'), ('Vacation', 'Vacation'), ('Repairs', 'Repairs')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
            ],
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='insurance_account_percentage',
            field=Main.fields.IntegerRangeField(default=25),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='investment_account_percentage',
            field=Main.fields.IntegerRangeField(default=25),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='savings_account_percentage',
            field=Main.fields.IntegerRangeField(default=50),
        ),
    ]
