# Generated by Django 3.1.5 on 2021-02-08 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0009_auto_20210208_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
