# Generated by Django 3.1.5 on 2021-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20210208_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
