# Generated by Django 3.1.5 on 2021-02-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_investmentinfo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentinfo',
            name='monthly_expenses',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentinfo',
            name='monthly_income',
            field=models.FloatField(),
        ),
    ]
