# Generated by Django 3.1.5 on 2021-02-11 09:05

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20210211_1004'),
    ]

    operations = [
        
    ]
