# Generated by Django 3.1.5 on 2021-02-11 10:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0012_auto_20210211_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Savings',
            new_name='Saving',
        ),
    ]
