# Generated by Django 3.1.5 on 2021-02-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20210211_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='Main.saving')),
            ],
        ),
    ]
