# Generated by Django 3.1.5 on 2021-02-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20210211_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.saving'),
        ),
    ]
