# Generated by Django 3.1.5 on 2021-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_saving_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='investmentMarkets',
            field=models.CharField(choices=[('Whole Life', 'Whole Life'), ('LTCA rider', 'LTCA rider'), ('SWL', 'SWL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investmentMarkets',
            field=models.CharField(choices=[('Mutual Funds', 'Mutual Funds'), ('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('ETFs', 'ETFs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='saving',
            name='investmentMarkets',
            field=models.CharField(choices=[('Family Support', 'Family Support'), ('Major Purchases', 'Major Purchases'), ('Vacation', 'Vacation'), ('Repairs', 'Repairs')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
