# Generated by Django 3.1.5 on 2021-02-11 22:16

import Main.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0019_auto_20210211_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment2',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(default='Investment', editable=False, max_length=50)),
                ('investmentMarkets', models.CharField(choices=[('Mutual Funds', 'Mutual Funds'), ('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('ETFs', 'ETFs')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
            ],
        ),
    ]
