# Generated by Django 3.1.5 on 2021-02-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_investment2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment2',
        ),
    ]
