# Generated by Django 3.1.5 on 2021-02-11 22:39

import Main.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0022_auto_20210211_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Insurance', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('investmentMarkets', models.CharField(choices=[('Whole Life', 'Whole Life'), ('LTCA rider', 'LTCA rider'), ('SWL', 'SWL')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Investment', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('investmentMarkets', models.CharField(choices=[('Mutual Funds', 'Mutual Funds'), ('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('ETFs', 'ETFs')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Savings', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('investmentMarkets', models.CharField(choices=[('Family Support', 'Family Support'), ('Major Purchases', 'Major Purchases'), ('Vacation', 'Vacation'), ('Repairs', 'Repairs')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='user',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
