# Generated by Django 3.1.5 on 2021-02-12 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0023_auto_20210211_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurances',
            name='investmentInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.investmentinfo'),
        ),
        migrations.AddField(
            model_name='investments',
            name='investmentInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.investmentinfo'),
        ),
        migrations.AddField(
            model_name='savings',
            name='investmentInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.investmentinfo'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
