# Generated by Django 3.1.5 on 2021-02-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20210212_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='investmentInfo',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.investmentinfo'),
        ),
    ]
