# Generated by Django 3.1.6 on 2021-02-12 23:20

import Main.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_auto_20210212_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummySavings',
            fields=[
                ('investmentinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main.investmentinfo')),
                ('name', models.CharField(default='Savings', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('investmentMarkets', models.CharField(choices=[('Family Support', 'Family Support'), ('Major Purchases', 'Major Purchases'), ('Vacation', 'Vacation'), ('Repairs', 'Repairs')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', Main.fields.IntegerRangeField()),
                ('investmentInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Main.investmentinfo')),
            ],
            bases=('Main.investmentinfo',),
        ),
    ]
