# Generated by Django 3.1.6 on 2021-02-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_dummysavings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummySavings',
        ),
    ]
