# Generated by Django 3.1.6 on 2021-02-17 21:27

import Main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_delete_dummysavings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurances',
            options={'verbose_name': 'Insurance', 'verbose_name_plural': 'Insurances'},
        ),
        migrations.AlterModelOptions(
            name='investments',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.AlterModelOptions(
            name='savings',
            options={'verbose_name': 'Saving', 'verbose_name_plural': 'Savings'},
        ),
        migrations.AlterField(
            model_name='insurances',
            name='percentage',
            field=Main.fields.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='percentage',
            field=Main.fields.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='percentage',
            field=Main.fields.IntegerRangeField(null=True),
        ),
    ]
