# Generated by Django 3.1.6 on 2021-02-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0035_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
