# Generated by Django 3.1.6 on 2021-02-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_remove_savings_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='category',
        ),
    ]
