# Generated by Django 3.1.6 on 2021-02-17 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0041_auto_20210217_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.category'),
        ),
    ]
