# Generated by Django 3.1.6 on 2021-02-18 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0042_auto_20210217_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.category')),
                ('investmentInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.investmentinfo')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.subcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Add Market',
                'verbose_name_plural': 'Add Markets',
            },
        ),
    ]
