# Generated by Django 3.1.6 on 2021-02-18 01:25

import Main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0043_addmarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmarket',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addmarket',
            name='percentage',
            field=Main.fields.IntegerRangeField(null=True),
        ),
    ]
