# Generated by Django 3.1.6 on 2021-02-22 13:29

import Main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0046_auto_20210222_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurances',
            name='percentage',
            field=Main.fields.DecimalRangeField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='percentage',
            field=Main.fields.DecimalRangeField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='percentage',
            field=Main.fields.DecimalRangeField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
