# Generated by Django 3.1.6 on 2021-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0047_auto_20210222_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurances',
            name='investmentMarkets',
            field=models.CharField(choices=[('Whole Life', 'Whole Life'), ('LTCA rider', 'LTCA rider'), ('SWL', 'SWL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='investmentMarkets',
            field=models.CharField(choices=[('Mutual Funds', 'Mutual Funds'), ('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('ETFs', 'ETFs')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='investmentMarkets',
            field=models.CharField(choices=[('Family Support', 'Family Support'), ('Major Purchases', 'Major Purchases'), ('Vacation', 'Vacation'), ('Repairs', 'Repairs')], max_length=50, null=True),
        ),
    ]
