# Generated by Django 3.1.6 on 2021-02-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0048_auto_20210222_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurances',
            name='investmentMarkets',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='investmentMarkets',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='investmentInfo',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='investmentMarkets',
        ),
    ]
