# Generated by Django 3.1.6 on 2021-02-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0049_auto_20210222_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMarket',
        ),
    ]
